### ISSUE TITLE
Version is Hardcoded

### ISSUE THREAD

**Issue by mcaulifn** [inverse-inc/ansible-packetfence#46]
https://github.com/inverse-inc/ansible-packetfence/blob/3b55ac7ca4420f5231709c229917167ddb9c9a01/packetfence/roles/packetfence_install/defaults/main.yml#L23

This does not allow any other version to be installed.

**Comment by nqb** [comment]
Hello @mcaulifn,

This variable is defined in `defaults/main.yml`, you should be able to override this variable with what you want from inventory or in other places.

Look at: https://github.com/inverse-inc/packetfence/blob/a1314ccb8664edd5a6a7353e68532e90b43113cf/ci/packer/zen/provisioners/inventory/group_vars/pfservers/packetfence_install.yml#L7-L9

This is how we build ZEN based on Debian 11 at release and it works as expected.

**Comment by mcaulifn** [comment]
That effectively requires the value to be set in two places. I feel like that is something module should abstract, making it easier on the user.
